In [1]:
import pandas
import re
import numpy
import scipy.spatial

file_sentences = open('sentences.txt')
sentences_list = []
words_list = []
words_dict = {}
num_sentences = 1

for line in file_sentences:
    sentences_list.append(line[:-2])
    
    for symbol in line:
        if symbol == '\n':
            num_sentences += 1
            
    line_words_list = re.split('[^a-z]', line.lower())
    for element in line_words_list:
        if element != '':
            words_list.append(element)

key = 0
for word in words_list:
    if words_dict.values().count(word) == 0:
        words_dict.update({key:word})
        key += 1

        
matrix = numpy.zeros((num_sentences, key))

sentence_number = 0
for sentence in sentences_list:
    for word in re.split('[^a-z]', sentence.lower()):
        for k in words_dict.keys():
            if word == words_dict[k]:
                matrix[sentence_number, k] += 1
    sentence_number += 1

cosdist_dict = {}
for i in range(1, num_sentences):
    cosdist_dict.update({i:scipy.spatial.distance.cosine(matrix[0,:], matrix[i,:])}) 

print cosdist_dict
print cosdist_dict.values()    
vals = cosdist_dict.values()[:]
vals.sort()
print vals

for i, j in cosdist_dict.items():
    if j == vals[0]:
        i1 = i
    if j == vals[1]:
        i2 = i


print i1, cosdist_dict[i1], i2, cosdist_dict[i2]

print words_dict
print sentences_list[1]
print matrix[1,:]


file_sentences.close()

file_result = open('submission-1.txt', 'w')
file_result.write(str(i1) + ' ' + str(i2))
file_result.close()

{1: 0.95275444087384664, 2: 0.86447381456421235, 3: 0.89517151632780823, 4: 0.77708871496985887, 5: 0.94023856953328033, 6: 0.7327387580875756, 7: 0.92587506833388988, 8: 0.88427248752843102, 9: 0.90550888174769317, 10: 0.83281653622739416, 11: 0.88047713906656067, 12: 0.83964325485254543, 13: 0.87035925528956715, 14: 0.87401184233025764, 15: 0.94427217874246472, 16: 0.84063618542208085, 17: 0.95664450152379399, 18: 0.94427217874246472, 19: 0.88854435748492944, 20: 0.84275727449171223, 21: 0.820715708599841}
[0.95275444087384664, 0.86447381456421235, 0.89517151632780823, 0.77708871496985887, 0.94023856953328033, 0.7327387580875756, 0.92587506833388988, 0.88427248752843102, 0.90550888174769317, 0.83281653622739416, 0.88047713906656067, 0.83964325485254543, 0.87035925528956715, 0.87401184233025764, 0.94427217874246472, 0.84063618542208085, 0.95664450152379399, 0.94427217874246472, 0.88854435748492944, 0.84275727449171223, 0.820715708599841]
[0.7327387580875756, 0.77708871496985887, 0.820

In [48]:
import re
string = 'wefew wefewf ewefwefwe e e e \n'
split_list = re.split('[^a-z]', string)
list1 = []
for e in split_list:
    list1.append(e)
print list1
print string

['wefew', 'wefewf', 'ewefwefwe', 'e', 'e', 'e', '', '']
wefew wefewf ewefwefwe e e e 



In [28]:
string

'wefew wefewf ewefwefwe e e e '

In [19]:
import pandas
list1 = ['1', 2]

In [20]:
len(list1)

2

In [34]:
print list1

None


In [41]:
aList = [123, 'xyz', 'zara', 'abc']
aList.append( 2009 )
print "Updated List : ", aList

Updated List :  [123, 'xyz', 'zara', 'abc', 2009]


In [59]:
dict1 = {}
dict1.values()

[]

In [41]:
list1 = range(10)

In [42]:
print list1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


34
1
2


In [41]:
matr = numpy.array(([3,5,6],[4,7,8],[9,10,11]))
print matr
print matr[0, :]

[[ 3  5  6]
 [ 4  7  8]
 [ 9 10 11]]
[3 5 6]


In [8]:
matr[2,3] = 1

In [9]:
matr[2,3]

1.0

In [8]:
dict1 = {1:'234',2:'34',3:'qwerty'}
print dict1[2]
for i in dict1.keys():
    print i
s = 'qwerty wefwf erf qwerty fweff__vwe f qwerty'
num = s.count(dict1[3])

for key, value in dict1.items():
    if value == '234':
        print key

34
1
2
3
1


In [18]:
print num

3


In [64]:
scipy.spatial.distance.cosine([1,2,3],[1,2,3])

0.0

In [75]:
arr = numpy.array(5)

In [76]:
print arr

5


In [78]:
arr.array.append(6)

AttributeError: 'numpy.ndarray' object has no attribute 'array'

In [2]:
import scipy

In [3]:
scipy.spatial.distance.cosine([11,2],[3,4])

AttributeError: 'module' object has no attribute 'spatial'

In [3]:
list1 = [4, 2, 7, 8, 4]
list1.sort()
print list1

[2, 4, 4, 7, 8]
